### ISSUE TITLE
データベースからweightを取得できない場合がある件について。

### ISSUE THREAD

**Issue by sonarAIT** [SystemEngineeringTeam/HackU-vol.1#45]
結論から申し上げますが、原因は特定できました。
![image](https://user-images.githubusercontent.com/67499131/90654447-5e598000-e27b-11ea-942f-b718a4ccf870.png)
これはtasksの画像です
![image](https://user-images.githubusercontent.com/67499131/90654530-70d3b980-e27b-11ea-99f8-1f80113eb7f7.png)
これはtask.goの84行目にlog.Println(weightID)を書いた結果の出力です。
どうやら、task.goの79行目のrows.Scanにおいて、途中で一つでもNULLが存在すると、途中でスキャンを放棄する？ようです（途中で放棄するかどうかは要検証ですが、少なくともweightIDは初期値である0のままになっています）

https://qiita.com/Neetless/items/cce3d256a3b879d6f9b3 
この記事を見る限り、rows.Scanを使用する際にrowsにNULLが含まれているときには不具合を引き起こすようです。
直し方がわからないのと、調べる体力が残っていないので、判明した事実をここに書き残します。以上。

**Comment by sonarAIT** [comment]
ちなみに、これは時間が登録できないバグが修正済みの'remove_deadline_bug'ブランチで行いました（masterブランチでも同じ実験を行いましたが、そもそも時間が必ずNULLになるので、あまり意味はありませんでした。）

**Comment by ReTKW** [comment]
nullを許可しない書き方になっていたので修正しました．
